In [1]:
import numpy as np
import scipy.stats as ss
import cv2
#import torch

def file_len(fname):
    with open(fname) as f:
        for i, l in enumerate(f):
            pass
    return i + 1
    
file = open("Data.txt", "r") 
fLen = file_len("Data.txt")
bgr = [0]*fLen
label = [0]*fLen
for idx, line in enumerate(file):
    temp = map(int, line.split())
    bgr[idx] = [temp[0], temp[1], temp[2]]
    label[idx] = temp[3]
bgr = np.array(bgr)
label = np.array(label)

skin_mean = bgr[:50589,:].mean(axis=0)
skin_var = bgr[:50589,:].var(axis=0)
nonSkin_mean = bgr[50589:,:].mean(axis=0)
nonSkin_var = bgr[50589:,:].var(axis=0)
skin_distbn = ss.multivariate_normal(mean = skin_mean, cov = skin_var)
nonSkin_distbn = ss.multivariate_normal(mean = nonSkin_mean, cov = nonSkin_var)


In [2]:
print skin_mean/255
print skin_var

[ 0.44639023  0.57472434  0.79976551]
[ 1739.0092018   1290.22894013  1426.94384388]


In [3]:
print nonSkin_mean
print nonSkin_var

[ 127.98836827  128.85303495  102.16741058]
[ 4390.21815255  4127.27179659  4125.52420851]


In [4]:
# load an image
import cv2
img = cv2.imread('img_119.jpg')

thresh = 0.5
for i in range(480):
    for j in range(640):
        pixel = img[i][j]
        val = skin_distbn.pdf(pixel)/(skin_distbn.pdf(pixel) + nonSkin_distbn.pdf(pixel))
        if val > thresh:
            #pass
            img[i][j] = [0, 0, 0]

cv2.imwrite('img_119.jpg', img)
